### ISSUE TITLE
Double Arch Structure Path

### ISSUE THREAD

**Issue by Xaneas** [yungnickyoung/YUNGs-Extras#3]
In the File [ConfiguredFeatureModule.java](https://github.com/YUNG-GANG/YUNGs-Extras/blob/d6a3a601e49926e7ebd49f13f2f79c63fa34c3f3/Common/src/main/java/com/yungnickyoung/minecraft/yungsextras/module/ConfiguredFeatureModule.java) the paths for the double arch structures point to the `arch` folder instead of the `double_arch` folder.
eg. `swamp/arch/swamp_double_arch_0` should be `swamp/double_arch/swamp_double_arch_0`.

Log file dumb a error and the double arch will not spawn.
eg. `Failed to create invalid feature yungsextras:swamp/arch/swamp_double_arch_3`

Edit: the File `swamp/arch/swamp_arch_11` is not existent but is in the file mentioned.

**Comment by yungnickyoung** [comment]
Good catch, thanks!
